set hlsearch
set ignorecase
set smartcase

set backup
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undofile
set undodir=~/.vim/undo//
set viminfo+=n~/.vim/viminfo
silent! call mkdir(expand(&backupdir), 'p', 0700)
silent! call mkdir(expand(&directory), 'p', 0700)
silent! call mkdir(expand(&undodir), 'p', 0700)

inoremap <Left> <C-G>U<Left>
inoremap <Right> <C-G>U<Right>
inoremap jj <Esc>
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>
nnoremap j gj
nnoremap k gk
nnoremap s "_x
nnoremap S "_S
nnoremap U <C-r>
nnoremap Y y$
nnoremap x "_x
nnoremap X "_X
vnoremap s "_x
vnoremap S "_S
vnoremap x "_x
vnoremap X "_X

set autoindent
set cursorline
set list
set listchars=eol:↲,tab:»·,trail:·,extends:»,precedes:«,nbsp:%
set number
set relativenumber

syntax on
set termguicolors
filetype plugin indent on

set clipboard=unnamedplus
