set hlsearch
set ignorecase
set smartcase
set viminfo+=n~/.vim/viminfo

set backup
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undofile
set undodir=~/.vim/undo//
silent! call mkdir(expand(&backupdir), 'p', 0700)
silent! call mkdir(expand(&directory), 'p', 0700)
silent! call mkdir(expand(&undodir), 'p', 0700)

nnoremap <silent> <Esc><Esc> :nohlsearch<CR>
nnoremap j gj
nnoremap k gk
inoremap jj <Esc>

set cursorline
set listchars=eol:↲,tab:»·,trail:·,extends:»,precedes:«,nbsp:%
set list
set number
set relativenumber
set smartindent

syntax enable
set termguicolors
filetype plugin indent on

set clipboard=unnamedplus
